export class EntityDto {
    number_id: number;
    entityId: string;
    attorneyname: string;
    attorneyId: string;
    entity: number;
    legalname: string;
    legalFormId: string;
    cnae: string;
    sic: string;
    college: string;
    lat: number;
    lng: number;
    mapZoom: number;
    legalActivityId: string;
    entityType: string;
    companyTaxId: string;
    googleAddress: string;
    country: number;
    region: number;
    province: number;
    business: number;
    company: number;
    city: string;
    postalCode: string;
    street: string;
    streetnumber: string;
    postfixAddress: string;
    longitude: string;
    latitude: string;
    telephone: string;
    fax: string;
    gdprId: string;
    upDate: string;
    registrationDate: string;
    quoteId: string
    policiesId: string;
    Bank1: string;
    AccountHolder1: string;
    Account1: string;
    Clabe1: string;
    Bank2: string;
    AccountHolder2: string;
    Account2: string;
    Clabe2: string;
    subAccount: string;
    balanceId: string
    commentsText: string;
    active: string;
    kardexId: string
    logo: string;
    perfilImg: string;
    entityAddress: any;
    email: string;
    accountNumber: number;
    currency:string;
    profile: {
        name: string;
        location: string;
        website: string;
        picture: string
    };
    createdBy: string;
    updatedBy: string;
}